version: '2.2'

services:
   mariadb:
      container_name: limesurvey_db
      image: mariadb:10.5.2-bionic
      environment:
         MYSQL_DATABASE: limesurvey
         MYSQL_ROOT_PASSWORD: secr3t
      ports:
         - 3306:3306
   limesurvey:
      container_name: limesurvey_service
      image: budtmo/limesurvey:3.22.14
      ports:
         - 8081:80
